// app/views/html/components/tags/Index.jsx
import React, { Component, PropTypes } from 'react'
import { Link } from 'react-router'
import queryString from 'query-string'

const { site } = __CONFIG__

import Breadcrumb from '../parts/Breadcrumb'

const title = '标签列表';

export default class IndexComponent extends Component {
  static contextTypes = {
    router: React.PropTypes.object.isRequired,
    fetch: React.PropTypes.func.isRequired,
    onChange: React.PropTypes.func.isRequired,
    toUrl: React.PropTypes.func.isRequired,
  }

  onChange = this.context.onChange

  state = {
    results: [],
    more: true,
    loading: false,
  }

  componentWillMount() {
    if (this.props.componentState) {
      this.setState(this.props.componentState)
      this.setMeta(this.props.componentState)
    }
  }

  componentDidMount() {
    if (!this.props.componentState) {
      this.fetch(this.props)
    } else if (this.state.messages) {
      this.props.setMessages(this.state.messages, 'danger', 'popup')
    }
  }


  componentWillReceiveProps(nextProps) {
    var location = this.props.location
    var nextLocation = nextProps.location
    if (location.key == nextLocation.key) {
      return
    }

    if (location.pathname == nextLocation.pathname && location.search == nextLocation.search) {
      return
    }
    if (!this.isMore) {
      this.setState({results:[], more: true})
    }
    this.isMore = false
    this.fetch(nextProps)
  }


  setMeta(state) {
    var location = this.props.location
    var page = parseInt(location.query.page || 1)
    if (isNaN(page)) {
      page = 1
    }

    var search = (location.query.search || '').trim()

    var meta = {
      title: [],
      'rel:alternate': [],
      'rel:canonical': [],
    }

    var query = {}

    if (search) {
      query.search = search
      meta.title.push('搜索 '+ search +' 的结果')
    }

    // 带有搜索 和页面列表的
    if (search) {
      meta.robots = 'none'
    }

    meta.title.push(title)

    if (page > 1) {
      query.page = page
      meta.title.push('第' + page + '页')
    }

    meta.title.push(site.title)

    meta['rel:canonical'].push({
      type: 'text/html',
      href: this.context.toUrl(location.pathname, query)
    });

    if (query.page > 1) {
      meta['rel:prev'] = {
        type: 'text/html',
        href: this.context.toUrl(location.pathname, Object.assign({}, query, {page:query.page == 2 ? undefined : query.page - 1}))
      }
    }

    if (state.more) {
      meta['rel:next'] = {
        type: 'text/html',
        href: this.context.toUrl(location.pathname, Object.assign({}, query, {page:query.page + 1}))
      }
    }

    this.props.setMeta(meta)
  }


  async fetch(props) {
    if (this.state.loading) {
      return false
    }
    this.setState({loading: true})
    try {
      var result = await this.context.fetch('/tags', props.location.query)
      result.loading = false
      result.results = this.state.results.concat(result.results)
      this.setState(result)
      this.setMeta(result)
    } catch (e) {
      props.setMessages([e, '请重试'], 'danger', 'popup')
      this.setState({loading: false})
    }
  }


  onMore = (e) => {
    this.isMore = true
  }

  render () {
    var location = this.props.location
    var query = location.query

    var menu = ''
    if (this.props.token.admin) {
      menu = (
      <section id="admin-menu">
        <ul id="admin-menu-fixed" className="nav flex-column">
          <li className="link-item">{this.props.location.query.state == -1 ? <Link to="/tags" className="link-link">已发布</Link> : <Link to="/tags?state=-1" className="link-link">已禁用</Link>}</li>
          <li  className="link-item"><Link to="/tags/create" className="link-link">创建</Link></li>
        </ul>
      </section>
      )
    }



    var page = parseInt(query.page || 1)
    if (isNaN(page)) {
      page = 1
    }
    var next
    var prev
    if (page > 1) {
      let search = queryString.stringify(Object.assign({}, query, {page:query.page == 2 ? undefined : query.page - 1}))
      prev = location.pathname + (search ? '?' + search : '')
    }
    if (this.state.more) {
      next = location.pathname + '?' + queryString.stringify(Object.assign({}, query, {page: page + 1}))
    }

    return (
      <div id="tags-index">
        <Breadcrumb>{title}</Breadcrumb>
        <main id="main" role="main">
          <section id="content">
            <h1 className="title">标签</h1>
            <ul className="tags-list">
              {this.state.results.map((tag, key) => {
                return (
                  <li key={tag._id}><Link to={tag.postUri} rel="tag" className="btn btn-outline-primary" title={tag.names[0]}>{tag.names[0] + '('+ tag.count +')'}</Link></li>
                )
              })}
            </ul>
            <nav className="navigation" role="navigation">
              {next ? <Link to={next} className="more" onClick={this.onMore} rel="next">{this.state.loading ? '载入中...' : '加载更多'}</Link> : <span className="more">全部已加载完毕</span>}
              {prev ? <Link to={prev} className="prev" rel="prev">上一页</Link> : ''}
              {next ? <Link to={next} className="next" rel="next">下一页</Link> : ''}
            </nav>
          </section>
          {menu}
        </main>
      </div>
    )
  }
}

// app/views/vue/views/tags/Index.vue
<template>
<main>
  <section id="content">
    <div id="tags-index">
      <h1 class="title">标签</h1>
      <ul class="tags-list">
        <li v-for="(tag, key) in tagList.results" :key="key"><router-link :to="tag.postUrl" rel="tag" class="btn btn-outline-primary" :title="tag.names[0]">{{tag.names[0] + '('+ tag.count +')'}}</router-link></li>
      </ul>
      <nav class="navigation pagination" role="navigation">
        <loading v-if="tagList.loading"></loading>
        <a v-else-if="tagList.more" :href="$pageNext" class="more" @click="$pageMore" rel="next">加载更多</a>
        <span v-else class="loaded">全部已加载完毕</span>
        <router-link v-if="$route.page > 1" :to="$pagePrev" class="prev" rel="prev">上一页</router-link>
        <router-link v-if="tagList.more" :to="$pageNext" class="next" rel="next">下一页</router-link>
      </nav>
    </div>
  </section>
  <section id="admin-menu" v-if="token.admin">
    <ul id="admin-menu-fixed" class="nav flex-column">
      <li class="link-item">
        <router-link to="/tags" class="nav-link" v-if="$route.query.state == -1">已发布</router-link>
        <router-link to="/tags?state=-1" class="nav-link" v-else>已禁用</router-link>
      </li>
      <li  class="link-item"><router-link to="/tags/create" class="link-link">创建</router-link></li>
    </ul>
  </section>
</main>
</template>
<style lang="sass">
@import "../../styles/variables"
#tags-index
  .title
    display: none
  .tags-list
    @include clearfix()
    list-style: none
    padding: 0
    margin: 0
    li
      float: left
    a
      display: block
      float: left
      margin: 0 1rem 1rem 0
  .pagination
    border: 0
    .next,
    .prev,
      display: none
</style>
<script>
import Vue from 'vue'
import { mapState } from 'vuex'

import site from 'config/site'


import {TAG_LIST} from '../../store/types'

const toUrl = Vue.filter('toUrl')

const title = '标签列表'

export default {
  data() {
    return {
      isMore: false,
    }
  },


  watch: {
    $route() {
      this.fetchAuto()
    }
  },

  methods: {
    async fetch({state, dispatch, commit}) {
      var route = state.route
      var add = this.isMore
      if (this.isMore) {
        this.isMore = false
      }
      await dispatch({
        type: TAG_LIST,
        add,
        path: route.path,
        query: route.query,
        fullPath: route.fullPath.split('#')[0],
      })
    },


    fetchAuto() {
      if (!__SERVER__ && this.$route.fullPath.split('#')[0] != this.tagList.fullPath) {
        this.fetch(this.$store)
      }
    },
  },

  computed: {
    ...mapState(['tagList', 'token'])
  },

  mounted() {
    this.fetchAuto()
  },

  headers({state}) {
    var route = state.route
    var query = {}

    var headers = {
      html: {
        prefix: 'og:http://ogp.me/ns#',
      },
      title: [],
      meta: [],
      link: [],
      breadcrumb: [],
    }
    var query = {}

    var page = parseInt(route.query.page || 1)
    if (isNaN(page) || page < 1) {
      page = 1
    }
    var search = (route.query.search || '').trim()


    if (search) {
      query.search = search
      headers.title.push('搜索 '+ search +' 的结果')
    }


    if (page > 1) {
      query.page = page
      headers.title.push('第' + page + '页')
    }

    // 带有搜索
    if (search) {
      headers.meta.push({name:'robots', content: 'none'})
    }



    headers.link.push({rel:'canonical', type: 'text/html', href: toUrl(route.path, query, state)})


    if (query.page > 1) {
      headers.link.push({rel:'prev', type: 'text/html', href: toUrl(route.path, Object.assign({}, query, {page:query.page == 2 ? undefined : query.page - 1}), state)})
    }

    if (state.tagList.more) {
      headers.link.push({rel:'next', type: 'text/html', href: toUrl(route.path, Object.assign({}, query, {page:query.page + 1}), state)})
    }

    headers.title.push(title, site.title)

    headers.breadcrumb.push(title)

    return headers
  }
}
</script>
