// app/views/vue/views/posts/Editor.vue
<template>
<main>
  <section id="content">
    <form id="posts-editor" role="form" method="post" class="form-horizontal" @submit="onSubmit" autocomplete="off">
      <messages></messages>
      <div class="form-group">
        <label for="title" class="form-label">标题: </label>
        <input type="text" class="form-control" name="title" v-model="title" id="title" placeholder="在此输入标题"  maxlength="64" required />
      </div>
      <div class="form-group">
        <label for="slug"  class="form-label">自定义地址: </label>
        <input type="text" class="form-control"  name="slug" minlength="3" maxlength="32" pattern="^[0-9a-z_-]{3,32}$"  id="slug" placeholder="只允许只用小写英文数字和下划线" v-model="slug" />
      </div>
      <div class="form-group">
        <label for="content" class="form-label">内容: </label>
        <markdown-editor :rows="20" placeholder="" :storage="true" v-model="content" />
      </div>
      <div class="form-group">
        <label for="tags" class="form-label">标签: </label>
        <tags-input id="tags" v-model="tags" />
      </div>

      <div class="form-group">
        <label for="page" class="form-label">文章类型: </label>
        <select name="page" id="page" class="form-control" v-model="page">
          <option value="">文章</option>
          <option value="1">页面</option>
        </select>
      </div>

      <div class="form-group">
        <label for="comment" class="form-label">评论: </label>
        <select name="comment" id="comment" class="form-control" v-model="comment">
          <option value="1">允许评论</option>
          <option value="">禁止评论</option>
        </select>
      </div>

      <div class="form-group">
        <button type="submit" :disabled="submitting || postRead.loading" class="btn btn-primary btn-lg btn-block">提交</button>
      </div>
    </form>
  </section>
</main>
</template>

<style>
</style>

<script>
import { mapState } from 'vuex'

import site from 'config/site'


import {POST_READ, MESSAGES} from '../../store/types'
import MarkdownEditor from '../../components/markdown/Editor'
import TagsInput from '../../components/TagsInput'

export default {

  data() {
    return {
      title: '',
      slug: '',
      content: '',
      tags: [],
      page: '',
      comment: '1',
      submitting: false,
    }
  },

  components: {
    MarkdownEditor,
    TagsInput,
  },

  methods: {
    async fetch({state, dispatch, commit}) {
      if (__SERVER__) {
        return
      }
      var route = state.route
      if (!route.params.slug) {
        return
      }
      await dispatch({
        type: POST_READ,
        path: '/' + route.params.slug,
        query: {update: true},
        fullPath: route.fullPath.split('#')[0],
      })
      this.setData()
    },
    fetchAuto() {
      if (__SERVER__) {
        return;
      }
      if (this.$route.fullPath.split('#')[0] == this.postRead.fullPath) {
        this.setData()
      } else {
        this.fetch(this.$store)
      }
    },
    setData() {
      var post = this.postRead
      this.title = post.title
      this.slug = post.slug
      this.content = post.content
      this.tags = post.tags.filter(tag => tag && tag.names.length)
      this.page = post.page ? '1' : ''
      this.comment = post.comment ? '1' : ''
    },
    async onSubmit(e) {
      e.preventDefault()
      const commit = this.$store.commit
      var slug = this.$route.params.slug

      var body = {...this.$data}
      body.tags = body.tags
        .filter(tag => !!tag)
        .map(tag => tag.names[0])

      try {
        this.submitting = true
        var result = await commit.fetch('/' + (slug ? slug : 'create'), {}, body)
        this.$router.push(result.url + '?message=' + (slug ? 'update' : 'create') + '&r='+ Date.now())
      } catch (e) {
        commit({
          ...e,
          type: MESSAGES,
          message: e.message
        })
      } finally {
        this.submitting = false
      }
    }
  },

  watch: {
    $route() {
      this.fetchAuto()
    },
  },

  computed: {
    ...mapState(['postRead'])
  },

  mounted() {
    this.fetchAuto()
  },

  headers({state}) {
    var title = state.route.params.slug ? '编辑文章' : '创建文章'
    return {
      title: [title, site.title],
      meta: [
        {name: 'robots', content:'none'},
      ],
      breadcrumb: [title],
    }
  }
}
</script>

// app/views/html/components/posts/Editor.jsx
import React, { Component, PropTypes } from 'react'
import { Link } from 'react-router'
import moment from 'moment'

import Editor from '../parts/markdown/Editor'
import Breadcrumb from '../parts/Breadcrumb'
import Messages from '../../containers/parts/Messages'

const { site } = __CONFIG__

export default class EditorComponent extends Component {
  static contextTypes = {
    router: React.PropTypes.object.isRequired,
    onChange: React.PropTypes.func.isRequired,
    fetch: React.PropTypes.func.isRequired,
  }

  onChange = this.context.onChange


  state = {
    content: '',
    tags: [],
    comment: true,
    disabled: false
  }


  componentDidMount() {
    this.props.setMeta({
      title:[this.props.params.slug ? '编辑文章' : '发布文章', site.title],
      robots: 'none',
    })
    this.fetch(this.props)
  }


  async fetch(props) {
    var slug = props.params.slug
    if (!slug) {
      return
    }
    this.setState({disabled: true})
    try {
      var result = await this.context.fetch('/' + slug)
      if (result.messages) {
        props.setMessages(result.messages, 'danger', 'popup')
        return
      }
      this.state.disabled = false
      this.setState(result)
    } catch (e) {
      props.setMessages([e, '请重试'], 'danger', 'popup')
    }
  }



  onAddTags = (e) => {
    e.preventDefault()
    var addTags = this.state.addTags || '';
    addTags = addTags.trim()
    if (!addTags) {
      return;
    }
    var indexs = this.state.tags.map((tag) => {
      if (typeof tag == 'string' || !tag) {
        return tag
      }
      return tag.names[0]
    })
    addTags = addTags.split(/'|"|;|:|,|\.|\/|\?|!|#|`|｀|；|：|’|‘|“|”|，|。|／|？/)
    addTags = addTags.map(name => name.trim()).filter(name => name && (name.length != 24 || !/^\w+$/.test(name)))
    var tags = this.state.tags.concat()
    for (let i = 0; i < addTags.length; i++) {
      let name = addTags[i]
      name = name[0].toUpperCase() + name.substr(1)
      if (indexs.indexOf(name) != -1) {
        continue
      }
      indexs.push(name)
      tags.push(name)
    }
    this.setState({tags, addTags:''})
  }

  onEnterTags = (e) => {
    if(e.keyCode == 13) {
      this.onAddTags(e)
    }
  }

  onRemoveTag(tag) {
    return (e) => {
      e.preventDefault()
      var tags = this.state.tags
      var index = tags.indexOf(tag)
      if (index != -1) {
        tags.splice(index, 1);
        this.setState({tags})
      }
    }
  }



  onSubmit = async (e) => {
    e.preventDefault();
    if (this.state.disabled) {
      return
    }
    var slug = this.props.params.slug
    var body = {
      title: this.state.title,
      slug: this.state.slug,
      content: this.state.content,
      page: this.state.page,
      comment: this.state.comment === true || this.state.comment === 'true' ? '1' : '',
      tags: [],
    }

    for (let i = 0; i < this.state.tags.length; i++) {
      let tag = this.state.tags[i]
      if (!tag) {
        continue
      }
      body.tags.push(typeof tag == 'string' ? tag : tag.names[0])
    }

    body.tags = body.tags.join(',')

    this.setState({disabled: true});
    try {
      var result = await this.context.fetch((slug ?  '/' + slug : '/create'), {}, body)
      if (result.messages) {
        this.props.setMessages(result)
        this.setState({disabled: false})
        return
      }
      this.context.router.push(result.uri + '?message=' + (slug ? 'update' : 'create') + '&r='+ Date.now())
    } catch (e) {
      this.props.setMessages(e)
      this.setState({disabled: false})
    }
  }


  render() {
    return (
      <div id="posts-editor">
        <Breadcrumb>{this.props.params.slug ? '编辑文章' : '发布文章'}</Breadcrumb>
        <main id="main" role="main">
          <section id="content">
            <form role="form" method="post" className="form-horizontal" onSubmit={this.onSubmit} autoComplete="off">
              <Messages />
              <div className="form-group">
                <label htmlFor="title" className="form-label">标题: </label>
                <input type="text" className="form-control" name="title" id="title" placeholder="在此输入标题" maxLength="64" required value={this.state.title || ''}  onChange={this.onChange()}/>
              </div>
              <div className="form-group">
                <label htmlFor="slug"  className="form-label">自定义地址: </label>
                <input type="text" className="form-control"  name="slug" minLength="3" maxLength="32" pattern="^[0-9a-z_]{3,32}$"  id="slug" placeholder="只允许只用小写英文数字和下划线" value={this.state.slug || ''} onChange={this.onChange()} />
              </div>
              <div className="form-group">
                <label htmlFor="content" className="form-label">内容: </label>
                <Editor id="content" rows="20" placeholder="" name="content"  value={this.state.content|| ''} onChange={this.onChange()} storage={true}></Editor>
              </div>
              <div className="form-group">
                <label htmlFor="tags" className="form-label">标签: </label>
                <div className="form-group">
                  <div className="input-group">
                    <input type="text" className="form-control" id="new-tags" name="add-tags" autoComplete="off" placeholder="" value={this.state.addTags || ''} onChange={this.onChange('addTags')} onKeyDown={this.onEnterTags} />
                    <div className="input-group-btn">
                      <button type="button" className="btn btn-secondary" onClick={this.onAddTags}>
                        添加
                      </button>
                    </div>
                  </div>
                  <p className="form-text">多个标签请用英文逗号（<code>,</code>）分开</p>
                  <div className="tags-list">
                    {this.state.tags.map((tag) => {
                      if (!tag) {
                        return
                      }
                      let name = typeof tag == 'string' ? tag : tag.names[0]
                      return (
                        <span key={name} className="name">{name}<span onClick={this.onRemoveTag(tag)}>×</span></span>
                      )
                    })}
                  </div>
                </div>
              </div>
              <div className="form-group">
                <label htmlFor="page" className="form-label">文章类型: </label>
                <select name="page" id="page" value={this.state.page ? '1' : ''} className="form-control" onChange={this.onChange()}>
                  <option value="">文章</option>
                  <option value="1">页面</option>
                </select>
              </div>
              <div className="form-group">
                <label htmlFor="comment" className="form-label">评论: </label>
                <select name="comment" id="comment" value={this.state.comment} className="form-control" onChange={this.onChange()}>
                  <option value={true}>允许评论</option>
                  <option value={false}>禁止评论</option>
                </select>
              </div>
              <div className="form-group">
                <button type="submit" disabled={this.state.disabled} className="btn btn-primary btn-lg btn-block">提交</button>
              </div>
            </form>
          </section>
        </main>
      </div>
    )
  }
}
