// app/views/vue/views/Posts/Read.vue
<template>
<main>
  <section id="content" v-if="postRead.loading">
    <loading size="xl" :middle="true"></loading>
  </section>
  <section id="content" v-else-if="!postRead._id">
  </section>
  <section id="content" v-else>
    <div id="posts-read">
      <article class="markdown entry hentry" itemscope itemtype="http://schema.org/BlogPosting">
        <header class="entry-header">
          <h1 class="entry-title">
            <router-link :to="postRead.url" rel="bookmark" title="postRead.title" itemprop="headline">{{postRead.title}}</router-link>
          </h1>
          <div class="entry-meta">
            <time class="entry-date" itemprop="datePublished" v-if="postRead.createdAt" :datetime="postRead.createdAt | fromDate" :title="postRead.createdAt | fromDate">{{postRead.createdAt | fromNow}}</time>
            <span class="entry-views">
              {{(postRead.meta.views || 0) + '次浏览'}}
            </span>
            <span class="comments-link">
              <router-link :to="postRead.url + '#comments'" rel="nofollow">{{(postRead.meta.comments || 0) + '条评论'}}</router-link>
            </span>
          </div>
        </header>
        <markdown-view class="content entry-content" itemprop="articleBody" :html="true" :children="postRead.htmlContent"></markdown-view>
        <footer class="entry-footer" v-if="postRead._id  && !postRead.page">
          <p>原文链接：<router-link :to="postRead.url">{{postRead.url | toUrl({}, this.$store.state)}}</router-link></p>
          <p>发表时间：<time class="entry-date" itemprop="datePublished" :datetime="postRead.createdAt | fromDate" :title="postRead.createdAt | fromDate">{{postRead.createdAt | fromDate('YYYY-MM-DD hh:mm:ss')}}</time></p>
          <p class="tag-links" v-if="postRead.tags.length">
            分类标签：<span itemprop="keywords">
              <router-link v-for="(tag, key) in postRead.tags" :key="key"  :to="tag.postUrl" rel="tag">{{tag.names[0]}}</router-link>
            </span>
          </p>
        </footer>
      </article>
      <nav class="pagination posts-pagination" v-if="postRead.prev || postRead.next">
        <router-link :to="postRead.prev.url" v-if="postRead.prev" class="prev" rel="prev">{{postRead.prev.title}}</router-link>
        <router-link :to="postRead.next.url" v-if="postRead.next" class="next" rel="next">{{postRead.next.title}}</router-link>
      </nav>
    </div>
  </section>
  <comment-section v-if="!postRead.loading && postRead._id" class="comments-inline"></comment-section>
  <section id="admin-menu" v-if="token.admin && postRead._id">
    <ul id="admin-menu-fixed" class="nav flex-column">
      <li class="nav-item">
        <router-link :to="postRead.url + '/update'" class="nav-link">编辑</router-link>
      </li>
      <li class="nav-item">
        <a href="#" @click="onRestore" class="nav-link" v-if="postRead.deletedAt">恢复</a>
        <a href="#" @click="onDelete" class="nav-link" v-else>删除</a>
      </li>
    </ul>
  </section>
</main>
</template>
<style lang="sass">
@import "../../styles/posts"
</style>
<script>
import Vue from 'vue'
import { mapState } from 'vuex'

import site from 'config/site'

import {POST_READ} from '../../store/types'
import CommentSection from './CommentSection'

const toUrl = Vue.filter('toUrl')
const fromDate = Vue.filter('fromDate')



export default {
  watch: {
    $route() {
      this.fetchAuto()
    }
  },

  components: {
    CommentSection
  },

  methods: {
    async fetch(store) {
      const {state, dispatch, commit} = store
      var route = state.route

      await dispatch({
        type: POST_READ,
        path: route.path,
        query: route.query,
        fullPath: route.fullPath.split('#')[0],
      })
      if (__SERVER__) {
        await CommentSection.methods.fetch(store)
      }
    },

    fetchAuto() {
      if (!__SERVER__ && this.$route.fullPath.split('#')[0] != this.postRead.fullPath) {
        this.fetch(this.$store)
      }
    },
    onDelete(e) {
      this.onRestore(e)
    },
    async onRestore(e) {
      var post = this.postRead
      const commit = this.$store.commit
      try {
        await commit.fetch(post.url +'/' + (post.deletedAt ? 'restore' : 'delete'), {}, {})
        await commit({
          type: POST_READ,
          add: true,
          state: {
            deletedAt: post.deletedAt ? null : new Date
          }
        })
      } catch (e) {
        e.name = 'popup'
        commit(e)
      }
    }
  },


  computed: {
    ...mapState(['postRead', 'token'])
  },

  mounted() {
    this.fetchAuto()
  },
  headers({state}) {
    var post = state.postRead

    var headers = {
      html: {
        prefix: 'og:http://ogp.me/ns/article#'
      },
      title: [],
      meta: [],
      link: [],
      breadcrumb: [],
    }
    if (!post._id) {
      headers.status = 404
      headers.statistics = false
      headers.title.push('文章内容', site.title)
      headers.breadcrumb.push('文章内容')
      return headers
    }
    headers.title.push(post.title, site.title)

    var keywords = post.tags.filter(tag => !!tag).map(tag => tag.names[0])

    headers.meta.push(
      {name:'description', content: post.description},
      {name:'keywords', content: keywords.join(',')}
    )

    headers.meta.push(
      {property:'og:type', content: 'article'},
      {property:'og:title', content: post.title},
      {property:'og:description', content: post.description}
    )

    if (post.images.length) {
      headers.meta.push({property:'og:image', content: post.images[0]})
    }

    headers.meta.push({property:'article:author', content: '恋月 @' + site.author})
    headers.meta.push({property:'article:tag', content: keywords.join(',')})
    headers.meta.push({property:'article:published_time', content: fromDate(post.createdAt)})
    headers.meta.push({property:'article:modified_time', content: fromDate(post.updatedAt)})


    headers.link.push({
      rel: 'canonical',
      type: "text/html",
      href: toUrl(post.url, null, state),
    })

    if (post.prev) {
      headers.link.push({
        rel: 'prev',
        type: "text/html",
        title: post.prev.title,
        href: toUrl(post.prev.url, null, state),
      })
    }

    if (post.next) {
      headers.link.push({
        rel: 'next',
        type: "text/html",
        title: post.next.title,
        href: toUrl(post.next.url, null, state),
      })
    }

    if (post.page) {
      headers.breadcrumb.push(post.title)
    } else {
      if (post.tags.length && post.tags[0]) {
        var tag = post.tags[0]
        headers.breadcrumb.push({url: tag.postUrl, name: tag.names[0]})
      }
      headers.breadcrumb.push('文章内容')
    }

    return headers
  }
}




</script>

// app/views/html/components/posts/Read.jsx
import React, { Component, PropTypes } from 'react'
import { Link } from 'react-router'
import queryString from 'query-string'
import moment from 'moment'

const { site } = __CONFIG__

import View from '../parts/markdown/View'
import Breadcrumb from '../parts/Breadcrumb'
import Comment from './Comment'

export default class ReadComponent extends Component {


  // 服务端拉数据
  static fetchServer(state, store, params, ctx) {
    var res;
    if (__SERVER__) {
      res = async () => {
        if (state.messages) {
          return
        }
        const Comments = require('../../../../viewModels/posts/comments/index');
        await Comments(ctx, null, {})
        state.comments = ctx.getViewState()
      }
      res = res()
    }
    return res;
  }

  static contextTypes = {
    router: React.PropTypes.object.isRequired,
    fetch: React.PropTypes.func.isRequired,
    toUrl: React.PropTypes.func.isRequired,
  }

  state = {
    meta: {},
    tags: [],
  }

  componentWillMount() {
    if (this.props.componentState) {
      this.setState(this.props.componentState);
      this.setMeta(this.props.componentState);
    }
  }


  componentDidMount() {
    if (!this.props.componentState) {
      this.fetch(this.props)
    } else if (this.state.messages) {
      this.props.setMessages(this.state.messages, 'danger', 'popup')
    }
  }




  setMeta(state) {
    if (state.messages) {
      this.props.setMeta({title: ['错误消息', site.title]});
      return
    }
    var tags = []
    if (state.tags) {
      for (var i = 0; i < state.tags.length; i++) {
        var tag = state.tags[i]
        if (tag && tag.names && tag.names.length) {
          tags.push(tag.names[0])
        }
      }
    }

    var meta = {
      title: [state.title, site.title],
      'rel:canonical': [],
    }
    meta['rel:canonical'].push({
      type: 'text/html',
      href: this.context.toUrl(state.uri)
    });
    meta.description = state.description
    meta.keywords = tags.join(',')

    if (state.prev) {
      meta['rel:prev'] = {
        type: 'text/html',
        href: this.context.toUrl(state.prev.uri),
        title: state.prev.title,
      }
    }

    if (state.next) {
      meta['rel:next'] = {
        type: 'text/html',
        href: this.context.toUrl(state.next.uri),
        title: state.next.title,
      }
    }

    meta['rel:alternate'] = {
      type: 'application/rss+xml',
      href: this.context.toUrl(state.uri, {view: 'rss'}),
      title:  state.title + ' » RSS 2.0',
    }


    meta['og:type'] = 'article'
    meta['og:title'] = state.title
    meta['og:description'] = state.description
    if (state.images.length) {
      meta['og:image'] = state.images[0]
    }
    meta['article:author'] = ['恋月 @' + site.author]
    meta['article:tag'] = meta.keywords
    meta['article:published_time'] = moment(state.createdAt).format()
    meta['article:modified_time'] = moment(state.updatedAt).format()
    this.props.setMeta(meta);
  }


  async fetch(props) {
    this.state = {
      meta: {},
      tags: [],
    }
    this.setState({})
    try {
      var state = await this.context.fetch(props.location.pathname)
      this.setState(state)
      this.setMeta(state)
      if (state.messages) {
        props.setMessages(state.messages, 'danger', 'popup')
      }
    } catch (e) {
      props.setMessages([e, '请重试'], 'danger', 'popup')
      return
    }
  }

  componentWillReceiveProps(nextProps) {
    var location = this.props.location
    var nextLocation = nextProps.location
    if (location.key == nextLocation.key) {
      return
    }
    if (location.pathname == nextLocation.pathname && location.search == nextLocation.search) {
      return
    }
    this.fetch(nextProps)
  }

  onDelete = async (e) => {
    e.preventDefault();
    try {
      var result = await this.context.fetch(this.state.uri +'/delete', {}, {})
      if (result.messages) {
        this.props.setMessages(result.messages, 'danger', 'popup')
        return
      }
      this.context.router.push('/')
    } catch (e) {
      this.props.setMessages(e, 'danger', 'popup')
    }
  }

  onRestore = async (e) => {
    e.preventDefault();
    try {
      var result = await this.context.fetch(this.state.uri +'/restore', {}, {})
      if (result.messages) {
        this.props.setMessages(result.messages, 'danger', 'popup')
        return
      }
      this.context.router.push('/')
    } catch (e) {
      this.props.setMessages(e, 'danger', 'popup')
    }
  }


  render() {
    const post = this.state;

    var menu = ''
    if (post._id && this.props.token.admin) {
      menu = (
        <section id="admin-menu">
          <ul id="admin-menu-fixed" className="nav flex-column">
            <li className="nav-item"><Link to={post.uri + '/update'} className="nav-link">编辑</Link></li>
            <li className="nav-item">{post.deletedAt ? <a href="#" onClick={this.onRestore} className="nav-link">恢复</a> : <a href="#" onClick={this.onDelete} className="nav-link">删除</a>}</li>
          </ul>
        </section>
      )
    }

    var createdAt = post.createdAt ? moment(post.createdAt).format() : ''


    var footerTags = ''
    if (!post.page && post.tags && post.tags.length) {
      footerTags = (
        <p className="tag-links">
          分类标签：<span itemProp="keywords">
          {post.tags.map((tag) => {
            if (!tag || !tag.names || !tag.names.length) {
              return
            }
            return <Link key={tag._id}  to={tag.postUri} rel="tag">{tag.names[0]}</Link>
          })}
           </span>
        </p>
      )
    }
    var footer = ''
    if (!post.page && post._id) {
      footer = (
        <footer className="entry-footer">
          <p>原文链接：<Link to={this.state.uri}>{this.context.toUrl(this.state.uri)}</Link></p>
          <p>发表时间：<time className="entry-date" itemProp="datePublished" dateTime={createdAt} title={createdAt}>{createdAt ? moment(post.createdAt).format('YYYY-MM-DD hh:mm:ss') : ''}</time></p>
          {footerTags}
        </footer>
      )
    }

    var breadcrumb = []
    if (post.page) {
      breadcrumb.push(post.title)
    } else {
        if (post.tags && post.tags.length && post.tags[0]) {
          breadcrumb.push(<Link key="1" to={post.tags[0].postUri}>{post.tags[0].names[0]}</Link>)
        }
        breadcrumb.push('文章内容')
    }

    var commentProps = Object.assign({}, this.props)
    commentProps.inline = true
    commentProps.componentState = this.state.comments

    var nav = ''
    if (post.prev || post.next) {
      nav = (
        <nav className="pagination">
          {post.prev ? <Link to={post.prev.uri} className="prev" rel="prev">{post.prev.title}</Link> : ''}
          {post.next ? <Link to={post.next.uri} className="next" rel="next">{post.next.title}</Link> : ''}
        </nav>
      )
    }

    return (
      <div id="posts-read">
        <Breadcrumb>{breadcrumb}</Breadcrumb>
        <main id="main" role="main">
          <section id="content">
            <article className="markdown entry hentry" itemScope itemType="http://schema.org/BlogPosting">
              <header className="entry-header">
                <h1 className="entry-title">
                  <Link to={post.uri} rel="bookmark" title={post.title} itemProp="headline">{post.title}</Link>
                </h1>
                <div className="entry-meta">
                  <time className="entry-date" itemProp="datePublished" dateTime={createdAt} title={createdAt}>{createdAt ? moment(post.createdAt).fromNow() : ''}</time>
                  <span className="entry-views">
                    {post._id ? post.meta.views + '次浏览' : ''}
                  </span>
                  <span className="comments-link">
                    <Link href={post.uri + "#comments"} rel="nofollow">{(post.meta.comments  ? post.meta.comments : 0) + '条评论'}</Link>
                  </span>
                </div>
              </header>
              <View className="content entry-content" itemProp="articleBody" html={true}>{post.htmlContent}</View>
              {footer}
            </article>
            {nav}
          </section>
          <Comment {...commentProps}></Comment>
          {menu}
        </main>
      </div>
    )
  }
}
