// app/views/react/views/Comment/Index.js
import React, { Component, PropTypes } from 'react'
import { connect } from 'react-redux'
import { Link } from 'react-router-dom'
import queryString from 'query-string'
import moment from 'moment'

import site from 'config/site'

import actions from '../../actions'

import Loading from '../../components/Loading'

import Messages from '../../components/Messages'

import Main from '../../components/Main'

import View from '../../components/Markdown/View'


const title = '评论管理'





@connect(state => ({
  commentList: state.get('commentList'),
  router: state.get('router'),
}))
export default class Comment extends Component {
  static contextTypes = {
    fetch: React.PropTypes.func.isRequired,
    getPath: PropTypes.func.isRequired,
    onChange: React.PropTypes.func.isRequired,
  }

  onChange = this.context.onChange

  state = {
    loading: false,
  }

  componentWillMount() {
    if (__SERVER__) {
      return
    }
    this.componentWillReceiveProps(this.props)
  }

  componentDidMount() {
    var email = localStorage.getItem('email')
    if (email) {
      this.setState({email})
    }
    var author = localStorage.getItem('author')
    if (author) {
      this.setState({author})
    }
  }


  componentWillReceiveProps(nextProps) {
    var props = this.props
    if (this.state.loading || nextProps.commentList.get('path') == this.context.getPath(nextProps)) {
      return
    }
    if (!this.isMore) {
      this.props.dispatch(actions.clearCommentList())
    } else if (!props.commentList.get('more')) {
      return
    }
    this.isMore = false
    this.fetch(nextProps)
  }


  onDelete(comment) {
    return async (e) => {
      e.preventDefault();
      try {
        var result = await this.context.fetch( '/' + comment.getIn(['post', '_id']) + '/comments/' + comment.get('_id') +'/delete', {}, {})
        if (result.messages) {
          this.props.dispatch(actions.setMessages(result.messages, 'danger', 'popup'))
          return
        }
        var results = this.props.commentList.get('results')
        var index = results.indexOf(comment)
        if (index != -1) {
          results = results.splice(index, 1);
          this.props.dispatch(actions.setCommentList({results}))
        }
      } catch (e) {
        this.props.dispatch(actions.setMessages(e, 'danger', 'popup'))
      }
    }
  }



  onRestore(comment) {
    return async (e) => {
      e.preventDefault();
      try {
        var result = await this.context.fetch( '/' + comment.getIn(['post', '_id']) + '/comments/' + comment.get('_id') +'/restore', {}, {})
        if (result.messages) {
          this.props.dispatch(actions.setMessages(result.messages, 'danger', 'popup'))
          return
        }
        var results = this.props.commentList.get('results')
        var index = results.indexOf(comment)
        if (index != -1) {
          results = results.splice(index, 1);
          this.props.dispatch(actions.setCommentList({results}))
        }
      } catch (e) {
        this.props.dispatch(actions.setMessages(e, 'danger', 'popup'))
      }
    }
  }


  onMore = (e) => {
    e.preventDefault();
    this.isMore = true
    this.props.dispatch(actions.router.push(e.target.pathname + e.target.search))
  }


  onReply(parent) {
    return (e) => {
      e && e.preventDefault()
      this.setState({parent}, () => {
        this.refs.content && this.refs.content.focus()
      })
    }
  }


  async fetch(props) {
    if (__SERVER__) {
      return
    }
    if (this.state.loading) {
      return false
    }
    this.setState({loading: true})
    await props.dispatch(actions.addCommentList({path: this.context.getPath(props)}))
    try {
      var result = await this.context.fetch(props.location.pathname, props.location.search)
      await props.dispatch(actions.addCommentList(result))
    } catch (e) {
      await props.dispatch(actions.setMessages(e, 'danger', 'popup'))
    } finally {
      this.setState({loading: false})
    }
  }






  onSubmit = async (e) => {
    e.preventDefault();
    if (this.state.disabled) {
      return
    }

    var parent = this.state.parent

    var body = {
      author: this.state.author,
      email: this.state.email,
      content: this.state.content,
    }

    body.parent = parent.get('_id')

    this.setState({disabled: true});

    try {
      var result = await this.context.fetch(parent.getIn(['post', 'commentUrl']) + '/create', {}, body)
      if (result.messages) {
        this.props.dispatch(actions.setMessages(result))
        this.setState({disabled: false})
        return
      }
      this.setState({parent: null, content: ''})
      this.props.dispatch(actions.addCommentList({results: [result]}))
      localStorage.setItem('email', body.email)
      localStorage.setItem('author', body.author)
    } catch (e) {
      this.props.dispatch(actions.setMessages(e))
    } finally {
      this.setState({disabled: false});
    }
  }



  render () {
    var commentList = this.props.commentList

    var locationQuery = queryString.parse(this.props.location.search);

    var headers = {
      title: [title, site.title],
      breadcrumb: [title],
      meta: [
        {name: 'robots', content:'none'},
      ],
    }


    var navigation = ''
    if (commentList.get('more')) {
      let id = commentList.get('results').size ? commentList.get('results').get(-1).get('_id') : undefined
      let to = '/comments?' + queryString.stringify(Object.assign({}, locationQuery, {id}))
      navigation = <nav className="navigation pagination" role="navigation">
        {!this.state.loading && commentList.get('more') ? <Link to={to} className="more" onClick={this.onMore} rel="next">加载更多</Link> : ''}
        {this.state.loading ? <Loading></Loading> : ''}
      </nav>
    }


    var section = <section id="comments">
      <ol id="comments-list">
        {commentList.get('results').map((comment) => {
          var createdAt = moment(comment.get('createdAt')).format()
          var parent = comment.get('parent')
          var post = comment.get('post') && comment.get('post').get ?  comment.get('post') : null
          var says
          if (parent) {
            says = <span className="says">对 <strong>{parent.get('author')}</strong> 说</span>
          } else {
            says = <span className="says">说</span>
          }
          var form = ''
          if (this.state.parent && this.state.parent.get('_id') == comment.get('_id')) {
            form = <form role="form" method="post" id="comments-form" onSubmit={this.onSubmit}>
              <Messages/>
              <div className="form-group">
                <label htmlFor="author">名称：</label>
                <input id="author" name="author" className="form-control" placeholder="在此输入你的姓名" type="text" value={this.state.author || ''} maxLength="32" required onChange={this.onChange()} />
              </div>
              <div className="form-group">
                <label htmlFor="email">电子邮件：</label>
                <input id="email" name="email" className="form-control" type="email"  placeholder="请输入你的电子邮箱" value={this.state.email || ''} maxLength="64" required onChange={this.onChange()} />
              </div>
              <div className="form-group">
                <label htmlFor="comment-content">评论内容：</label>
                  {this.state.parent ? <span className="reply-info">您正在回复 <strong>{this.state.parent.author}</strong> 的评论 <a rel="nofollow" className="cancel-reply" href="#" onClick={this.onReply(null)}>点击这里取消回复。</a></span> : ''}
                <textarea id="comment-content" name="content" className="form-control"  ref="content" value={this.state.content || ''} maxLength="8192" required onChange={this.onChange()} ></textarea>
                <p>支持 <code>MarkDown</code> 代码, <code>Html</code> 标签</p>
              </div>
              <div className="form-group">
                <button type="submit" className="btn btn-primary btn-block btn-lg" disabled={this.state.disabled}>提交</button>
              </div>
            </form>
          }

          return (
            <li key={comment.get('_id')} className={comment.get('admin') ? 'comment-admin' : ''}>
              <header className="comment-meta">
                <div className="comment-author"><img src={comment.get('avatar')} className="avatar photo" /></div>
                <div className="actions">
                  {comment.get('deletedAt') ? <a className="restore" href="#" rel="nofollow" onClick={this.onRestore(comment)}>恢复</a> : <a className="delete" href="#" rel="nofollow" onClick={this.onDelete(comment)}>删除</a>}
                  {post && post.get('comment') ? <a className="reply" href="#" rel="nofollow" onClick={this.onReply(comment)}>回复</a> : ''}
                </div>
                <div className="text">
                  <span className="author vcard">{comment.get('author')}</span>
                  {post ? <span className="title">在 <Link to={post.get('url')} title={post.get('title')}>{post.get('title').length > 16 ? post.get('title').substr(0, 13) + '...' : post.get('title')}</Link></span> : ''}
                  {says}
                  <span className="time"><time dateTime={createdAt} title={createdAt}>{moment(comment.get('createdAt')).fromNow()}</time></span>
                </div>
              </header>
              <View className="content comment-content" html={true}>{(comment.get('htmlContent') || '')}</View>
              {form}
            </li>
          )
        })}
      </ol>
      {navigation}
    </section>


    var menu = <section id="admin-menu">
      <ul id="admin-menu-fixed" className="nav flex-column">
        <li className="nav-item">{locationQuery.deleted ? <Link to={this.props.location.pathname} className="nav-link">已发布</Link> : <Link to={this.props.location.pathname + "?deleted=1"} className="nav-link">回收站</Link>}</li>
      </ul>
    </section>


    return <Main {...headers}>
      {section}
      {menu}
    </Main>
  }
}

// app/views/vue/views/Comment.vue
<template>
<main>
  <section id="comments">
    <ol id="comments-list">
      <li v-for="(comment, key) in commentList.results" :key="key"  :class="comment.admin ?  'comment-admin' : null">
        <header class="comment-meta">
          <div class="comment-author"><img :src="comment.avatar" class="avatar photo" /></div>
          <div class="actions">
            <a class="restore" href="#" v-if="token.admin && comment.deletedAt" rel="nofollow" @click.prevent="onRestore(comment)">恢复</a>
            <a class="delete" href="#" v-else-if="token.admin" rel="nofollow" @click.prevent="onDelete(comment)">删除</a>
            <a class="reply" href="#" rel="nofollow" v-if="comment.post && comment.post.comment" @click.prevent="onReply(comment)">回复</a>
          </div>
          <div class="text">
            <span class="author vcard">{{comment.author}}</span>
            <span class="title" v-if="comment.post && comment.post._id">在 <router-link :to="comment.post.url" :title="comment.post.title">{{comment.post.title.length > 16 ? comment.post.title.substr(0, 13) + '...' : comment.post.title}}</router-link></span>
            <span class="says" v-if="comment.parent">对 <strong>{{comment.parent.author}}</strong> 说</span>
            <span class="says" v-else>说</span>
            <span class="time"><time :datetime="comment.createdAt | fromDate" :title="comment.createdAt | fromDate">{{comment.createdAt | fromNow}}</time></span>
          </div>
        </header>
        <markdown-view class="content comment-content" :html="true" :children="comment.htmlContent"></markdown-view>
        <form role="form" method="post" id="comments-form" @submit="onSubmit" v-if="parent && parent._id == comment._id">
          <messages />
          <div class="form-group">
            <label for="author">名称：</label>
            <input id="author" name="author" class="form-control" placeholder="在此输入你的姓名" type="text" v-model="author" maxLength="32" required />
          </div>
          <div class="form-group">
            <label for="email">电子邮件：</label>
            <input id="email" name="email" class="form-control" type="email"  placeholder="请输入你的电子邮箱" v-model="email" maxLength="64" required />
          </div>
          <div class="form-group">
            <label for="comment-content">评论内容：</label>
            <span class="reply-info" v-if="parent">您正在回复 <strong>{{parent.author}}</strong> 的评论 <a rel="nofollow" class="cancel-reply" href="#" @click.prevent="onReply(null)">点击这里取消回复。</a></span>
            <textarea id="comment-content" name="content" class="form-control"  ref="content" v-model="content" maxLength="8192" required></textarea>
            <p>支持 <code>MarkDown</code> 代码, <code>Html</code> 标签</p>
          </div>
          <div class="form-group">
            <button type="submit" :disabled="submitting || commentList.loading" class="btn btn-primary btn-lg btn-block">提交</button>
          </div>
        </form>
      </li>
    </ol>
    <nav class="navigation pagination" role="navigation" v-if="commentList.more">
      <loading v-if="commentList.loading" />
      <a v-else :href="pageNext" class="more" @click="pageMore" rel="next">加载更多</a>
    </nav>
  </section>
  <section id="admin-menu" v-if="token.admin">
    <ul id="admin-menu-fixed" class="nav flex-column">
      <li class="nav-item">
        <router-link :to="$route.path" class="nav-link" v-if="$route.query.deleted">已发布</router-link>
        <router-link :to="$route.path + '?deleted=1'" class="nav-link" v-else>回收站</router-link>
      </li>
    </ul>
  </section>
</main>
</template>

<style lang="sass">
@import "../styles/comments"
</style>
<script>
import { mapState } from 'vuex'

import site from 'config/site'
import pagination from '../mixins/pagination'

import {COMMENT_LIST} from '../store/types'

export default {

  data() {
    return {
      parent: null,
      submitting: false,
      email: '',
      author: '',
      content: '',
    }
  },


  computed: {
    pageNextQuery() {
      var id = undefined
      var comments = this.commentList.results
      if (comments.length) {
        id = comments[comments.length - 1]._id
      }
      return {id}
    },
    ...mapState(['commentList', 'token'])
  },


  mixins: [
    pagination
  ],

  watch: {
    author() {
      if (this.author != localStorage.getItem('author')) {
        localStorage.setItem('author', this.author)
      }
    },
    email() {
      if (this.email != localStorage.getItem('email')) {
        localStorage.setItem('email', this.email)
      }
    },
    $route() {
      this.fetchAuto()
    },
  },

  methods: {
    async fetch({state, dispatch, commit}) {
      if (__SERVER__) {
        return
      }

      var route = state.route
      var add = this.isMore
      if (this.isMore) {
        this.isMore = false
      }

      await dispatch({
        type: COMMENT_LIST,
        add,
        path: '/comments',
        query: route.query,
        fullPath: route.fullPath.split('#')[0],
      })

      if (this.isMore) {
        this.isMore = false
      }
    },


    fetchAuto() {
      if (!__SERVER__ && this.$route.fullPath.split('#')[0] != this.commentList.fullPath) {
        this.fetch(this.$store)
      }
    },

    async onDelete(comment) {
      const commit = this.$store.commit
      try {
        await commit.fetch('/' + comment.post._id + '/comments/' + comment._id +'/' + (commit.deletedAt ? 'restore' : 'delete'), {}, {})
        var state = {...this.commentList}
        state.results = [].concat(state.results)
        state.results.splice(state.results.indexOf(comment), 1)
        commit({
          type: COMMENT_LIST,
          state,
        })
      } catch (e) {
        e.name = 'popup'
        commit(e)
      }
    },

    onRestore(comment) {
      return this.onDelete(comment)
    },

    onReply(parent) {
      this.parent = parent
      if (parent) {
        this.$nextTick(() => {
          this.$refs.content[0].focus()
        })
      }
    },

    async onSubmit(e) {
      e.preventDefault()

      const commit = this.$store.commit
      try {
        this.submitting = true
        var body = {...this.$data}
        body.parent = body.parent._id

        var comment = await commit.fetch('/' + this.parent.post._id + '/comments/create', {}, body)
        this.content = ''

        commit({
          type: COMMENT_LIST,
          add: true,
          state: {
            results: [comment],
          },
        })
        this.content = ''
        this.onReply(null)
      } catch (e) {
        commit(e)
      } finally {
        this.submitting = false
      }
    },
  },

  mounted() {
    this.fetchAuto()

    var email = localStorage.getItem('email')
    if (email) {
      this.email = email
    }
    var author = localStorage.getItem('author')
    if (author) {
      this.author = author
    }
  },

  headers({state}) {
    var title = '评论管理'
    return {
      title: [title, site.title],
      meta: [
        {name: 'robots', content:'none'},
      ],
      breadcrumb: [title],
    }
  }
}
</script>
