// app/views/html/components/parts/Messages.jsx
import React, { Component, PropTypes } from 'react'
export default class MessagesComponent extends Component {

  static propTypes = {
    messages: React.PropTypes.object.isRequired,
    closeMessages: React.PropTypes.func.isRequired,
    name: React.PropTypes.string,
    close: React.PropTypes.func,
  }

  static defaultProps = {
    name: '',
  }

  close(e) {
    e && e.preventDefault();
    this.props.closeMessages(this.props.name);
    this.props.close && this.props.close()
  }

  componentWillUnmount() {
    this.close()
  }

  render () {
    const data = this.props.messages[this.props.name] || {};
    const messages = data.messages || [];
    var  type = data.type || 'danger'
    if (type == 'error') {
      type = 'danger'
    }
    return (
      <div role="alert" className={['alert', 'alert-' + type, 'messages'].join(' ')} style={{display: messages.length && !data.close ? '' : 'none'}}>
        <button type="button" className="close" onClick={this.close.bind(this)}><span>×</span></button>
        {
          messages.map(function(message, i) {
            return <p key={i}>{message.message}</p>
          })
        }
      </div>
    )
  }
}

// app/views/vue/components/Messages.vue
<template>
<div role="alert" :class="['alert', 'alert-' + type, 'messages']" v-show="messages.length && !close">
    <button type="button" class="close" @click="onClose"><span>×</span></button>
    <p v-for="(message, key) in messages" :key="key">{{typeof message == 'string' ? message : message.message}}</p>
</div>
</template>
<script>
import { MESSAGES_CLOSE } from '../store/types'
export default {
  props: {
    name: {
      type: String,
      default: '',
    },
  },
  computed: {
    data() {
      return this.$store.state.messages[this.name] || {}
    },
    messages() {
      return this.data.messages || []
    },
    type() {
      var type = this.data.type
      if (!type || type == 'error') {
        type = 'danger'
      }
      return type
    },
    close() {
      return this.data.close
    },
  },
  methods: {
    onClose(e) {
      e.preventDefault()
      this.$store.commit({type: MESSAGES_CLOSE, name: this.name})
    }
  },
}
</script>
