// app/views/react/components/Markdown/Editor.js
import React, { Component } from 'react'
import { Link } from 'react-router'

import Storage from '../Storage/Button'

export default class Editor extends Component {

  static defaultProps = {
    className: '',
    value: '',
  }

  state = {
  }



  onStorageSelect = (files) => {
    var editor = this.state.editor
    editor.focus()
    if (!files.length) {
      return
    }
    var selection = editor.getSelection().trim()

    var values = []
    for (let i = 0; i < files.length; i++) {
      let file = files[i];
      let name = selection || file.name
      if (selection) {
        name = name.replace(/^\s*\[(.*)\]\(.*\)\s*$/, '$1')
        if (name != selection) {
          let image = '!['+ name.replace(/([\[\]{}()~\\\\])/g, '') +']('+ file.original +')'
          values.push('['+ image +']('+ selection.replace(/^\s*\[.*\]\((.*)\)\s*$/, '$1') +')');
          continue
        }
        selection = ''
      }

      name = name.replace(/([\[\]{}()~\\\\])/g, '')
      values.push('!['+ name +']('+ file.original +')');
    }
    if (values.length > 1) {
      values.unshift('')
      values.push('')
      values = values.join('\n')
    } else {
      values = values.join('\n')
    }
    editor.replaceSelection(values)
  }

  componentDidUpdate() {
    if (this.state.editor && this.props.input.value != this.state.editor.getValue()) {
      this.state.editor.setValue(this.props.input.value)
    }
  }

  componentDidMount() {
    if (!__SERVER__) {
      require.ensure([], (require) => {
        const CodeMirror = require('codemirror');
        require('codemirror/mode/markdown/markdown');
        require('codemirror/mode/gfm/gfm');
        require('codemirror/addon/selection/active-line');
        require('codemirror/addon/display/placeholder');
        require('codemirror/addon/dialog/dialog');
        require('codemirror/addon/search/searchcursor');
        require('codemirror/addon/search/search');
        var editor = CodeMirror(this.refs.editor, {
          lineNumbers: true,
          styleActiveLine: true,
          mode: "gfm",
          gitHubSpice: false,
          placeholder: this.props.placeholder,
          value: this.props.input.value,
        });
        this.setState({editor})
        editor.setSize(null, (this.props.rows ? this.props.rows : 10) * 20);
        editor.on('change', () => {
          this.props.input.onChange(editor.getValue())
        });
      }, 'codemirror-markdown')
    }
  }

  render() {
    var className = this.props.className
    var storage = this.props.storage
    className +=  ' markdown-editor form-control'
    return (
      <div className="markdown">
        <div className={className} ref="editor"></div>
        {storage ? <Storage select={this.onStorageSelect}>添加附件</Storage> : ''}
      </div>
    )
  }
}

// app/views/vue/components/markdown/Editor.vue
<template>
  <div class="markdown ">
    <div class="form-control markdown-editor" ref="editor"></div>
  </div>
</template>
<style lang="sass">
@import "~codemirror/lib/codemirror.css"
@import "~codemirror/addon/dialog/dialog.css"
.markdown
  .markdown-editor
    padding: 0
  .storage-button
    margin-top: 1rem
</style>
<script>
export default {
  props: {
    value: {
      type: String,
      default: '',
    },
    placeholder: {
      type: String,
    },
    rows: {
      type: Number,
    },
    id: {
      type: String,
    },
    storage: {
      type: Boolean,
      default: true,
    },
  },
  data() {
    return {
      editor: null
    }
  },
  watch: {
    value() {
      if (this.editor && this.editor.getValue() != this.value) {
        this.editor.setValue(this.value)
      }
    }
  },

  methods: {
    updateValue(value) {
      if (this.editor && this.editor.getValue() != value) {
        this.editor.setValue(value)
      }
      // 通过 input 事件发出数值
      this.$emit('input', value)
    }
  },

  mounted() {
    if (!__SERVER__) {
      require.ensure([], (require) => {
        const CodeMirror = require('codemirror');
        require('codemirror/mode/markdown/markdown');
        require('codemirror/mode/gfm/gfm');
        require('codemirror/addon/selection/active-line');
        require('codemirror/addon/display/placeholder');
        require('codemirror/addon/dialog/dialog');
        require('codemirror/addon/search/searchcursor');
        require('codemirror/addon/search/search');
        var editor = CodeMirror(this.$refs.editor, {
          lineNumbers: true,
          styleActiveLine: true,
          mode: "gfm",
          gitHubSpice: false,
          placeholder: this.placeholder,
          value: this.value,
        });
        this.editor = editor
        editor.setSize(null, (this.rows ? this.rows : 10) * 20);
        editor.on('change', () => {
          this.updateValue(editor.getValue())
        });
      }, 'codemirror-markdown')
    }
  }
}
</script>
