// app/views/html/components/posts/Index.jsx
import React, { Component, PropTypes } from 'react'
import { Link } from 'react-router'
import queryString from 'query-string'
import moment from 'moment'

const { site } = __CONFIG__

import View from '../parts/markdown/View'
import Breadcrumb from '../parts/Breadcrumb'

export default class IndexComponent extends Component {
  static contextTypes = {
    router: React.PropTypes.object.isRequired,
    fetch: React.PropTypes.func.isRequired,
    toUrl: React.PropTypes.func.isRequired,
  }

  state = {
    results: [],
    more: true,
    loading: false,
    links: false,
  }


  // 服务端拉数据
  static fetchServer(state, store, params, ctx) {
    var res;
    if (__SERVER__) {
      res = async () => {
        if (ctx.request.path == '/' && !ctx.request.search) {
          const Post = require('../../../../models/post');
          var post = await Post.findOne({slug: 'links'}, {excerpt: 1}).exec()
          if (post) {
            state.links = post.get('excerpt')
          }
        }
      }
      res = res()
    }
    return res;
  }

  componentWillMount() {
    if (this.props.componentState) {
      this.setState(this.props.componentState)
      this.setMeta(this.props.componentState)
    }
  }

  componentDidMount() {
    if (!this.props.componentState) {
      this.fetch(this.props)
    } else if (this.state.messages) {
      this.props.setMessages(this.state.messages, 'danger', 'popup')
    }
  }

  componentWillReceiveProps(nextProps) {
    var location = this.props.location
    var nextLocation = nextProps.location
    if (location.key == nextLocation.key) {
      return
    }

    if (location.pathname == nextLocation.pathname && location.search == nextLocation.search) {
      return
    }
    if (!this.isMore) {
      this.setState({results:[], tag: null, more: true})
    }
    this.isMore = false
    this.fetch(nextProps)
  }

  onMore = (e) => {
    this.isMore = true
  }

  setMeta(state) {
    var location = this.props.location
    var tag = state.tag

    var page = parseInt(location.query.page || 1)
    if (isNaN(page)) {
      page = 1
    }
    var search = (location.query.search || '').trim()

    var meta = {
      title: [],
      'rel:alternate': [],
      'rel:canonical': [],
    }

    var query = {}


    if (search) {
      query.search = search
      meta.title.push('搜索 '+ search +' 的结果')
    } else if (tag) {
      meta.title.push(tag.names[0])
      meta.keywords = tag.name
      meta.description = tag.description
    } else if (location.query.isPage) {
      meta.title.push('页面列表')
    } else {
      meta.keywords = site.keywords,
      meta.description = site.description
    }

    // 带有搜索 和页面列表的
    if (search || location.query.isPage) {
      meta.robots = 'none'
    }

    if (page > 1) {
      query.page = page
      meta.title.push('第' + page + '页')
    }
    meta.title.push(site.title)
    if (meta.title.length == 1) {
      meta.title.push(site.description)
    }


    meta['rel:canonical'].push({
      type: 'text/html',
      href: this.context.toUrl(location.pathname, query)
    });

    if (query.page > 1) {
      meta['rel:prev'] = {
        type: 'text/html',
        href: this.context.toUrl(location.pathname, Object.assign({}, query, {page:query.page == 2 ? undefined : query.page - 1}))
      }
    }
    if (state.more) {
      meta['rel:next'] = {
        type: 'text/html',
        href: this.context.toUrl(location.pathname, Object.assign({}, query, {page:query.page + 1}))
      }
    }
    meta['og:type'] = 'website'
    meta['og:title'] = meta.title.join(' - ')
    meta['og:description'] = meta.description

    meta['rel:alternate'].push({
      type: 'application/rss+xml',
      title:  site.title + ' » Feed',
      href: this.context.toUrl(location.pathname, Object.assign({}, query, {view: 'rss', page: undefined})),
    })

    this.props.setMeta(meta)
  }


  async fetch(props) {
    if (this.state.loading) {
      return false
    }
    this.setState({loading: true})
    try {
      var result = await this.context.fetch(props.location.pathname, props.location.query)
      if (result.messages) {
        props.setMessages(result, 'danger', 'popup')
      } else {
        result.results = this.state.results.concat(result.results)
      }
      result.loading = false
      this.setState(result)
      this.setMeta(result)
    } catch (e) {
      props.setMessages([e, '请重试'], 'danger', 'popup')
      this.setState({loading: false})
    }
    if (this.state.links === false && props.location.pathname == '/' && !props.location.search) {
      this.setState({links: ''})
      try {
        var result = await this.context.fetch('/links', {record: ''})
        if (result.excerpt) {
          this.setState({links: result.excerpt})
        }
      } catch (e) {
      }
    }
  }


  onTagState = async (e) => {
    e.preventDefault();
    var tag = this.state.tag
    var state = tag.state == -1 ? 0 : -1
    try {
      var result = await this.context.fetch(tag.uri +'/state', {}, {state})
      if (result.messages) {
        this.props.setMessages(result.messages, 'danger', 'popup')
        return
      }
      tag.state = state
      this.setState({tag})
    } catch (e) {
      this.props.setMessages(e, 'danger', 'popup')
    }
  }

  render () {
    var location = this.props.location
    var query = location.query
    var tag = this.state.tag
    var search = (query.search || '').trim()

    var page = parseInt(query.page || 1)
    if (isNaN(page)) {
      page = 1
    }
    var next
    var prev
    if (page > 1) {
      let search = queryString.stringify(Object.assign({}, query, {page:query.page == 2 ? undefined : query.page - 1}))
      prev = location.pathname + (search ? '?' + search : '')
    }
    if (this.state.more) {
      next = location.pathname + '?' + queryString.stringify(Object.assign({}, query, {page: page + 1}))
    }

    var breadcrumb
    if (search) {
      breadcrumb = '搜索结果'
    } else if (tag) {
      breadcrumb = tag.names[0]
    } else if (this.props.params && this.props.params.tag) {
      breadcrumb = '标签'
    } else if (location.query.isPage) {
      breadcrumb = '页面列表'
    } else {
      breadcrumb = '文章列表'
    }


    var title = ''
    if (search) {
      title = <h1 className="title">搜索<strong>{search}</strong>的结果</h1>
    } else if (this.state.tag) {
      var tag = this.state.tag
      title = <h1 className="title">标签<Link to={'/tag-' + tag.postUri} title={tag.names[0]} rel="tag">{tag.names[0]}</Link>下的文章</h1>
    } else if (location.query.isPage) {
      title = <h1 className="title">页面列表</h1>
    }


    var adminMenu = ''
    if (this.props.token.admin) {
      tag = this.state.tag
      adminMenu = (
      <section id="admin-menu">
        <ul id="admin-menu-fixed" className="nav flex-column">
          <li className="nav-item">{this.props.location.query.deleted ? <Link to="/" className="nav-link">已发布</Link> : <Link to="/?deleted=1" className="nav-link">回收站</Link>}</li>
          <li className="nav-item">{query.isPage ? <Link to='/' className="nav-link">文章列表</Link> :  <Link to="/?isPage=1" className="nav-link">页面列表</Link>}</li>
          <li className="nav-item"><Link to="/create" className="nav-link">创建文章</Link></li>
          {tag && tag.state != -1 ? <li className="nav-item"><Link to={tag.uri + '/update'} className="nav-link">编辑标签</Link></li> : ''}
          {tag ? (<li className="nav-item"><a href="#" onClick={this.onTagState} className="nav-link">{tag.state == -1 ? '启用标签' : '禁用标签'}</a></li>) : ''}
          <li className="nav-item"><Link to="/comments" className="nav-link">评论管理</Link></li>
        </ul>
      </section>
      )
    }


    return (
      <div id="posts-index">
        <Breadcrumb>{breadcrumb}</Breadcrumb>
        <main id="main" role="main">
          <section id="content">
            {title}
            {this.state.results.map((post) => {
              var createdAt = post.createdAt ? moment(post.createdAt).format() : ''
              var content = post.excerpt || ''
              content  += '<p><a href="'+ post.uri +'" class="more-link">继续阅读 »</a></p>'
              return (
                <article key={post._id} className="post entry hentry"  itemScope itemType="http://schema.org/BlogPosting">
                  <header className="entry-header">
                    <h2 className="entry-title">
                      <Link to={post.uri} rel="bookmark" title={post.title} itemProp="headline">{post.title}</Link>
                    </h2>
                    <div className="entry-meta">
                      <time className="entry-date" itemProp="datePublished" dateTime={createdAt} title={createdAt}>{createdAt ? moment(post.createdAt).fromNow() : ''}</time>
                      <span className="comments-link">
                        <a href="#comments" rel="nofollow">{(post.meta.comments  ? post.meta.comments : 0) + '条评论'}</a>
                      </span>
                    </div>
                  </header>
                  {<View className="content entry-content" itemProp="articleBody" html={true}>{content}</View>}
                </article>
              )
            })}
            <nav className="navigation" role="navigation">
              {next ? <Link to={next} className="more" onClick={this.onMore} rel="next">{this.state.loading ? '载入中...' : '加载更多'}</Link> : <span className="more">全部已加载完毕</span>}
              {prev ? <Link to={prev} className="prev" rel="prev">上一页</Link> : ''}
              {next ? <Link to={next} className="next" rel="next">下一页</Link> : ''}
            </nav>
          </section>
          {location.pathname == '/' && !location.search && this.state.links ? <section id="links" dangerouslySetInnerHTML={{__html: '<h2 class="title">友情链接</h2>' + this.state.links}}></section> : ''}
          {adminMenu}
        </main>
      </div>
    )
  }
}

// app/views/vue/views/posts/Index.vue
<template>
<main>
  <section id="content">
    <div id="posts-index">
      <h1 class="title" v-if="$route.query.search && $route.query.search.trim()">搜索<strong>{{$route.query.search}}</strong>的结果</h1>
      <h1 class="title" v-else-if="postList.tag">标签<router-link :to="postList.tag.postUrl" :title="postList.tag.names[0]" rel="tag">{{postList.tag.names[0]}}</router-link>下的文章</h1>
      <h1 class="title" v-else-if="$route.query.isPage">页面列表</h1>
      <h1 class="title" v-else>{{siteTitle}}</h1>
      <article v-for="(post, key) in postList.results" :key="key" class="post entry hentry"  itemscope itemtype="http://schema.org/BlogPosting">
        <header class="entry-header">
          <h2 class="entry-title">
            <router-link :to="post.url" rel="bookmark" :title="post.title" itemprop="headline">{{post.title}}</router-link>
          </h2>
          <div class="entry-meta">
            <time class="entry-date" itemprop="datePublished" :datetime="post.createdAt | fromDate" :title="post.createdAt | fromDate">{{post.createdAt | fromNow}}</time>
            <span class="comments-link">
              <router-link :to="post.url + '#comments'" rel="nofollow">{{(post.meta.comments || 0) + '条评论'}}</router-link>
            </span>
          </div>
        </header>
        <markdown-view class="content entry-content" itemprop="articleBody" :html="true" :children="content(post)"></markdown-view>
      </article>
      <nav class="navigation pagination" role="navigation">
        <loading v-if="postList.loading"></loading>
        <a v-else-if="postList.more" :href="$pageNext" class="more" @click="$pageMore" rel="next">加载更多</a>
        <span v-else class="loaded">全部已加载完毕</span>
        <router-link v-if="$route.page > 1" :to="$pagePrev" class="prev" rel="prev">上一页</router-link>
        <router-link v-if="postList.more" :to="$pageNext" class="next" rel="next">下一页</router-link>
      </nav>
    </div>
  </section>
  <section id="links" v-if="$route.fullPath == '/'" v-html="linksExcerpt"></section>
  <section id="admin-menu" v-if="token.admin">
    <ul id="admin-menu-fixed" class="nav flex-column">
      <li class="nav-item">
        <router-link to="/" class="nav-link" v-if="$route.query.deleted">已发布</router-link>
        <router-link to="/?deleted=1" class="nav-link" v-else>回收站</router-link>
      </li>
      <li class="nav-item">
        <router-link to='/' class="nav-link" v-if="$route.query.isPage">文章列表</router-link>
        <router-link to="/?isPage=1" class="nav-link" v-else>页面列表</router-link>
      </li>
      <li class="nav-item">
        <router-link to="/create" class="nav-link">创建文章</router-link>
      </li>
      <li class="nav-item" v-if="postList.tag && postList.tag.state != -1">
        <router-link :to="postList.tag.url + '/update'" class="nav-link">编辑标签</router-link>
      </li>
      <li class="nav-item" v-if="postList.tag">
        <a href="#" @click="onTagState" class="nav-link">{{postList.tag.state == -1 ? '启用标签' : '禁用标签'}}</a>
      </li>
      <li class="nav-item">
        <router-link to="/comments" class="nav-link">评论管理</router-link>
      </li>
    </ul>
  </section>
</main>
</template>
<style lang="sass">
@import "../../styles/posts"
</style>
<script>
import Vue from 'vue'
import { mapState } from 'vuex'

import site from 'config/site'

import {LINKS, POST_LIST, MESSAGES} from '../../store/types'

const toUrl = Vue.filter('toUrl')



export default {
  data() {
    return {
      siteTitle: site.title,
    }
  },


  watch: {
    $route() {
      this.fetchAuto()
    }
  },

  methods: {
    async fetch({state, dispatch, commit}) {
      var route = state.route
      var add = this.isMore
      if (this.isMore) {
        this.isMore = false
      }
      await dispatch({
        type: POST_LIST,
        add,
        path: route.path,
        query: route.query,
        fullPath: route.fullPath.split('#')[0],
      })

      if (this.isMore) {
        this.isMore = false
      }

      if (state.route.fullPath == '/' && !state.links.excerpt) {
        await dispatch({
          type: LINKS,
        })
      }
    },
    fetchAuto() {
      if (!__SERVER__ && this.$route.fullPath.split('#')[0] != this.postList.fullPath) {
        this.fetch(this.$store)
      }
    },
    content(post) {
      return post.excerpt + '<p><a href="'+ post.url +'" class="more-link">继续阅读 »</a></p>'
    },

    async onTagState(e) {
      e.preventDefault();
      var tag = this.postList.tag
      var state = tag.state == -1 ? 0 : -1
      const commit = this.$store.commit
      try {
        await commit.fetch(tag.url +'/state', {}, {state})
        commit({
          type: POST_LIST,
          add: true,
          state: {
            tag: {...tag, state}
          }
        })
      } catch (e) {
        commit({
          ...e,
          name: 'popup',
          type: MESSAGES,
          message: e.message
        })
      }
    }
  },

  computed: {
    linksExcerpt() {
      return '<h2 class="title">友情链接</h2>' + this.links.excerpt
    },
    ...mapState(['postList', 'links', 'token'])
  },

  mounted() {
    this.fetchAuto()
  },

  headers({state}) {
    var route = state.route
    var query = {}

    var search = route.query.search ? route.query.search.trim() : false
    var tag = state.postList.tag
    var page = parseInt(route.query.page || 1)
    if (isNaN(page)) {
      page = 1
    }

    var headers = {
      html: {
        prefix: 'og:http://ogp.me/ns/website#'
      },
      title: [],
      meta: [],
      link: [],
      breadcrumb: [],
    }

    if (search) {
      headers.title.push('搜索 '+ search +' 的结果')
      headers.meta.push({name:'robots', content: 'none'})

      headers.breadcrumb.push('搜索结果')
    } else if (route.query.isPage) {
      headers.title.push('页面列表')
      headers.meta.push({name:'robots', content: 'none'})

      headers.breadcrumb.push('页面列表')
    } else if (tag) {
      headers.title.push(tag.names[0])
      headers.meta.push({name: 'keywords', content: tag.names.join(',')})
      headers.meta.push({name: 'description', content: tag.description})
      headers.meta.push({property: 'og:description', content: tag.description})

      headers.breadcrumb.push(tag.names[0])
    } else {
      headers.meta.push({name: 'keywords', content: site.keywords.join(',')})
      headers.meta.push({name: 'description', content: site.description})
      headers.meta.push({property: 'og:description', content: site.description})

      headers.breadcrumb.push('文章列表')
    }

    if (page > 1) {
      query.page = page
      headers.title.push('第' + page + '页')
    }

    headers.title.push(site.title)
    if (headers.title.length == 1) {
      headers.title.push(site.description)
    }

    headers.meta.push({property: 'og:type', content: 'website'})
    headers.meta.push({property: 'og:title', content: headers.title.join(' - ')})


    headers.link.push({rel:'canonical', type: 'text/html', href: toUrl(route.path, query, state)})


    if (query.page > 1) {
      headers.link.push({rel:'prev', type: 'text/html', href: toUrl(route.path, Object.assign({}, query, {page:query.page == 2 ? undefined : query.page - 1}), state)})
    }

    if (state.postList.more) {
      headers.link.push({rel:'next', type: 'text/html', href: toUrl(route.path, Object.assign({}, query, {page:(query.page ? query.page + 1 : 2)}), state)})
    }

    headers.link.push({rel:'alternate', type: 'application/rss+xml', title: site.title + ' » Feed', href: toUrl(route.path, Object.assign({}, query, {view: 'rss', page: undefined}), state)})


    return headers
  },
}
</script>
