// app/views/react/views/Posts/Read/Index.js
import React, { Component, PropTypes } from 'react'
import { connect } from 'react-redux'
import { Link } from 'react-router-dom'
import queryString from 'query-string'
import moment from 'moment'

import site from 'config/site'

import actions from '../../../actions'


import View from '../../../components/Markdown/View'
import Loading from '../../../components/Loading'

import Main from '../../../components/Main'

import Comment from '../Comment'





@connect(state => ({
  postRead: state.get('postRead'),
  router: state.get('router'),
  token: state.get('token'),
}))
export default class Read extends Component {
  static contextTypes = {
    fetch: PropTypes.func.isRequired,
    getPath: PropTypes.func.isRequired,
    toUrl: PropTypes.func.isRequired,
  }

  state = {
    loading: false,
  }


  async fetch(props) {
    if (this.state.loading) {
      return false
    }
    this.setState({loading: true})
    var path = this.context.getPath(props)
    await props.dispatch(actions.setPostRead({path}))
    try {
      var result = await this.context.fetch(props.location.pathname, props.location.search)
      result.path = path
      await props.dispatch(actions.setPostRead(result))
    } catch (e) {
      await props.dispatch(actions.setMessages(e, 'danger', 'popup'))
    } finally {
      this.setState({loading: false})
    }
  }


  componentWillMount() {
    if (__SERVER__) {
      return
    }
    this.componentWillReceiveProps(this.props)
  }

  componentWillReceiveProps(nextProps) {
    var props = this.props
    if (this.state.loading || nextProps.postRead.get('path') == this.context.getPath(nextProps)) {
      return
    }
    props.dispatch(actions.clearPostRead())
    this.fetch(nextProps)
  }



  onDelete = async (e) => {
    e.preventDefault();
    try {
      var result = await this.context.fetch(this.props.postRead.get('url') +'/delete', {}, {})
      this.props.dispatch(actions.clearPostRead())
      this.props.dispatch(actions.clearPostList())

      this.props.history.push(this.props.location.pathname + '?r=' + Date.now())
    } catch (e) {
      this.props.dispatch(actions.setMessages(e, 'danger', 'popup'))
    }
  }

  onRestore = async (e) => {
    e.preventDefault();
    try {
      var result = await this.context.fetch(this.props.postRead.get('url') +'/restore', {}, {})

      this.props.dispatch(actions.clearPostRead())
      this.props.dispatch(actions.clearPostList())

      this.props.history.push(this.props.location.pathname + '?r=' + Date.now())
    } catch (e) {
      this.props.dispatch(actions.setMessages(e, 'danger', 'popup'))
    }
  }




  render () {
    var post = this.props.postRead;
    if (this.state.loading || !post.get('_id')) {
      return <Main
        status={this.state.loading ? 200 : 404}
        title={["文章内容", site.title]}
        meta={[
          {name: 'robots', content:'none'},
        ]}
        breadcrumb={['文章内容']}
        statistics={false}
        >
        <section id="content">{this.state.loading ? <Loading size="xl" middle={true} /> : ''}</section>
      </Main>
    }



    var prev = post.get('prev')
    var next = post.get('next')
    var createdAt = moment(post.get('createdAt')).format()
    var postUrl = post.get('url') || '/'

    var headers = {
      html: {},
      title: [],
      meta: [],
      link: [],
      breadcrumb: [],
    }

    headers.html.prefix = 'og:http://ogp.me/ns/article#'
    headers.title.push(post.get('title'), site.title)


    var keywords = post.get('tags').filter(tag => !!tag).map(tag => tag.getIn(['names', 0]))

    headers.meta.push(
      {name:'description', content: post.get('description')},
      {name:'keywords', content: keywords.join(',')}
    )

    headers.meta.push(
      {property:'og:type', content: 'article'},
      {property:'og:title', content: post.get('title')},
      {property:'og:description', content: post.get('description')}
    )

    if (post.get('images').size) {
      headers.meta.push({property:'og:image', content: post.getIn(['images', 0])})
    }

    headers.meta.push({property:'article:author', content: '恋月 @' + site.author})
    headers.meta.push({property:'article:tag', content: keywords.join(',')})
    headers.meta.push({property:'article:published_time', content: createdAt})
    headers.meta.push({property:'article:modified_time', content: moment(post.get('updatedAt')).format()})


    headers.link.push({
      rel: 'canonical',
      type: "text/html",
      href: this.context.toUrl(postUrl),
    })

    if (prev) {
      headers.link.push({
        rel: 'prev',
        type: "text/html",
        title: prev.get('title'),
        href: this.context.toUrl(prev.get('url')),
      })
    }

    if (next) {
      headers.link.push({
        rel: 'next',
        type: "text/html",
        title: next.get('title'),
        href: this.context.toUrl(next.get('url')),
      })
    }


    if (post.get('page')) {
      headers.breadcrumb.push(post.get('title'))
    } else {
      if (post.get('tags').size && post.getIn(['tags', 0])) {
        var tag = post.getIn(['tags', 0])
        headers.breadcrumb.push({to: tag.get('postUrl'), name: tag.getIn(['names', 0])})
      }
      headers.breadcrumb.push('文章内容')
    }


    var footerTags = ''
    if (!post.get('page') && post.get('tags').size) {
      footerTags = <p className="tag-links">
        分类标签：<span itemProp="keywords">
        {post.get('tags').map((tag) => {
          if (!tag) {
            return
          }
          return <Link key={tag.get('_id')}  to={tag.get('postUrl')} rel="tag">{tag.getIn(['names', 0])}</Link>
        })}
         </span>
      </p>
    }


    var footer = ''
    if (!post.get('page') && post.get('_id')) {
      footer = <footer className="entry-footer">
        <p>原文链接：<Link to={postUrl}>{this.context.toUrl(postUrl)}</Link></p>
        <p>发表时间：<time className="entry-date" itemProp="datePublished" dateTime={createdAt} title={createdAt}>{createdAt ? moment(post.get('createdAt')).format('YYYY-MM-DD hh:mm:ss') : ''}</time></p>
        {footerTags}
      </footer>
    }







    var menu = ''
    if (post.get('_id') && this.props.token.get('admin')) {
      menu = (
        <section id="admin-menu">
          <ul id="admin-menu-fixed" className="nav flex-column">
            <li className="nav-item"><Link to={postUrl + '/update'} className="nav-link">编辑</Link></li>
            <li className="nav-item">{post.get('deletedAt') ? <a href="#" onClick={this.onRestore} className="nav-link">恢复</a> : <a href="#" onClick={this.onDelete} className="nav-link">删除</a>}</li>
          </ul>
        </section>
      )
    }

    var pagination = ''

    if (prev || next) {
      pagination = <nav className="pagination posts-pagination">
        {prev ? <Link to={prev.get('url')} className="prev" rel="prev">{prev.get('title')}</Link> : ''}
        {next ? <Link to={next.get('url')} className="next" rel="next">{next.get('title')}</Link> : ''}
      </nav>
    }

    return <Main {...headers}>
      <section id="content">
        <div id="posts-read">
          <article className="markdown entry hentry" itemScope itemType="http://schema.org/BlogPosting">
            <header className="entry-header">
              <h1 className="entry-title">
                <Link to={postUrl} rel="bookmark" title={post.get('title')} itemProp="headline">{post.get('title')}</Link>
              </h1>
              <div className="entry-meta">
                <time className="entry-date" itemProp="datePublished" dateTime={createdAt} title={createdAt}>{moment(post.get('createdAt')).fromNow()}</time>
                <span className="entry-views">
                  {post.getIn(['meta', 'views']) + '次浏览'}
                </span>
                <span className="comments-link">
                  <Link to={postUrl + "#comments"} rel="nofollow">{post.getIn(['meta', 'comments']) + '条评论'}</Link>
                </span>
              </div>
            </header>
            <View className="content entry-content" itemProp="articleBody" html={true}>{post.get('htmlContent')}</View>
            {footer}
          </article>
          {pagination}
        </div>
      </section>
      <Comment inline={true} location={this.props.location} history={this.props.history} match={this.props.match} />
      {menu}
    </Main>
  }
}

// app/views/vue/views/Posts/Read.vue
<template>
<main>
  <section id="content" v-if="postRead.loading">
    <loading size="xl" :middle="true"></loading>
  </section>
  <section id="content" v-else-if="!postRead._id">
  </section>
  <section id="content" v-else>
    <div id="posts-read">
      <article class="markdown entry hentry" itemscope itemtype="http://schema.org/BlogPosting">
        <header class="entry-header">
          <h1 class="entry-title">
            <router-link :to="postRead.url" rel="bookmark" title="postRead.title" itemprop="headline">{{postRead.title}}</router-link>
          </h1>
          <div class="entry-meta">
            <time class="entry-date" itemprop="datePublished" v-if="postRead.createdAt" :datetime="postRead.createdAt | fromDate" :title="postRead.createdAt | fromDate">{{postRead.createdAt | fromNow}}</time>
            <span class="entry-views">
              {{(postRead.meta.views || 0) + '次浏览'}}
            </span>
            <span class="comments-link">
              <router-link :to="postRead.url + '#comments'" rel="nofollow">{{(postRead.meta.comments || 0) + '条评论'}}</router-link>
            </span>
          </div>
        </header>
        <markdown-view class="content entry-content" itemprop="articleBody" :html="true" :children="postRead.htmlContent"></markdown-view>
        <footer class="entry-footer" v-if="postRead._id  && !postRead.page">
          <p>原文链接：<router-link :to="postRead.url">{{postRead.url | toUrl({}, this.$store.state)}}</router-link></p>
          <p>发表时间：<time class="entry-date" itemprop="datePublished" :datetime="postRead.createdAt | fromDate" :title="postRead.createdAt | fromDate">{{postRead.createdAt | fromDate('YYYY-MM-DD hh:mm:ss')}}</time></p>
          <p class="tag-links" v-if="postRead.tags.length">
            分类标签：<span itemprop="keywords">
              <router-link v-for="(tag, key) in postRead.tags" :key="key"  :to="tag.postUrl" rel="tag">{{tag.names[0]}}</router-link>
            </span>
          </p>
        </footer>
      </article>
      <nav class="pagination posts-pagination" v-if="postRead.prev || postRead.next">
        <router-link :to="postRead.prev.url" v-if="postRead.prev" class="prev" rel="prev">{{postRead.prev.title}}</router-link>
        <router-link :to="postRead.next.url" v-if="postRead.next" class="next" rel="next">{{postRead.next.title}}</router-link>
      </nav>
    </div>
  </section>
  <comment-section v-if="!postRead.loading && postRead._id" class="comments-inline"></comment-section>
  <section id="admin-menu" v-if="token.admin && postRead._id">
    <ul id="admin-menu-fixed" class="nav flex-column">
      <li class="nav-item">
        <router-link :to="postRead.url + '/update'" class="nav-link">编辑</router-link>
      </li>
      <li class="nav-item">
        <a href="#" @click="onRestore" class="nav-link" v-if="postRead.deletedAt">恢复</a>
        <a href="#" @click="onDelete" class="nav-link" v-else>删除</a>
      </li>
    </ul>
  </section>
</main>
</template>
<style lang="sass">
@import "../../styles/posts"
</style>
<script>
import Vue from 'vue'
import { mapState } from 'vuex'

import site from 'config/site'

import {POST_READ} from '../../store/types'
import CommentSection from './CommentSection'

const toUrl = Vue.filter('toUrl')
const fromDate = Vue.filter('fromDate')



export default {
  watch: {
    $route() {
      this.fetchAuto()
    }
  },

  components: {
    CommentSection
  },

  methods: {
    async fetch(store) {
      const {state, dispatch, commit} = store
      var route = state.route

      await dispatch({
        type: POST_READ,
        path: route.path,
        query: route.query,
        fullPath: route.fullPath.split('#')[0],
      })
      if (__SERVER__) {
        await CommentSection.methods.fetch(store)
      }
    },

    fetchAuto() {
      if (!__SERVER__ && this.$route.fullPath.split('#')[0] != this.postRead.fullPath) {
        this.fetch(this.$store)
      }
    },
    onDelete(e) {
      this.onRestore(e)
    },
    async onRestore(e) {
      var post = this.postRead
      const commit = this.$store.commit
      try {
        await commit.fetch(post.url +'/' + (post.deletedAt ? 'restore' : 'delete'), {}, {})
        await commit({
          type: POST_READ,
          add: true,
          state: {
            deletedAt: post.deletedAt ? null : new Date
          }
        })
      } catch (e) {
        e.name = 'popup'
        commit(e)
      }
    }
  },


  computed: {
    ...mapState(['postRead', 'token'])
  },

  mounted() {
    this.fetchAuto()
  },
  headers({state}) {
    var post = state.postRead

    var headers = {
      html: {
        prefix: 'og:http://ogp.me/ns/article#'
      },
      title: [],
      meta: [],
      link: [],
      breadcrumb: [],
    }
    if (!post._id) {
      headers.status = 404
      headers.statistics = false
      headers.title.push('文章内容', site.title)
      headers.breadcrumb.push('文章内容')
      return headers
    }
    headers.title.push(post.title, site.title)

    var keywords = post.tags.filter(tag => !!tag).map(tag => tag.names[0])

    headers.meta.push(
      {name:'description', content: post.description},
      {name:'keywords', content: keywords.join(',')}
    )

    headers.meta.push(
      {property:'og:type', content: 'article'},
      {property:'og:title', content: post.title},
      {property:'og:description', content: post.description}
    )

    if (post.images.length) {
      headers.meta.push({property:'og:image', content: post.images[0]})
    }

    headers.meta.push({property:'article:author', content: '恋月 @' + site.author})
    headers.meta.push({property:'article:tag', content: keywords.join(',')})
    headers.meta.push({property:'article:published_time', content: fromDate(post.createdAt)})
    headers.meta.push({property:'article:modified_time', content: fromDate(post.updatedAt)})


    headers.link.push({
      rel: 'canonical',
      type: "text/html",
      href: toUrl(post.url, null, state),
    })

    if (post.prev) {
      headers.link.push({
        rel: 'prev',
        type: "text/html",
        title: post.prev.title,
        href: toUrl(post.prev.url, null, state),
      })
    }

    if (post.next) {
      headers.link.push({
        rel: 'next',
        type: "text/html",
        title: post.next.title,
        href: toUrl(post.next.url, null, state),
      })
    }

    if (post.page) {
      headers.breadcrumb.push(post.title)
    } else {
      if (post.tags.length && post.tags[0]) {
        var tag = post.tags[0]
        headers.breadcrumb.push({url: tag.postUrl, name: tag.names[0]})
      }
      headers.breadcrumb.push('文章内容')
    }

    return headers
  }
}




</script>
