// app/views/vue/views/errors/NotFound.vue
<template>
<main>
  <section id="content">
    <div id="not-found">
    </div>
  </section>
</main>
</template>

<style lang="sass">
$www: #111

.red
  color: red
.animate
  color: $www
  animation: fade 1s
</style>

<script>
import site from 'config/site'


import {MESSAGES} from '../../store/types'

export default {
  watch: {
    $route() {
      this.messageAuto()
    },
  },

  methods: {
    messageAuto() {
      if (__SERVER__) {
        return
      }
      this.$store.commit({
        type: MESSAGES,
        name: 'popup',
        message: '您请求的页面不存在'
      })
    }
  },

  mounted() {
    this.messageAuto()
  },


  headers({state}) {
    var title = '错误消息'
    return {
      status: 404,
      title: [title, site.title],
      meta: [
        {name: 'robots', content:'none'},
      ],
      breadcrumb: [title],
    }
  }
}
</script>

// app/views/html/components/NotFound.jsx
import React, { Component, PropTypes } from 'react'
import { Link, IndexLink } from 'react-router'
import Breadcrumb from './parts/Breadcrumb'

export default class NotFoundComponent extends Component {
  static fetchServer(state, store, params, ctx) {
    var res;
    if (__SERVER__) {
      res = async () => {
        if (ctx.status < 400) {
          ctx.status = 404
        }
      }
      res = res()
    }
    return res;
  }

  state = {}

  componentWillMount() {
    if (this.props.componentState) {
      this.setState(this.props.componentState)
    }
    this.props.setMeta({
      title: ['错误消息', __CONFIG__.site.title],
      robots: 'none',
    })
  }

  componentDidMount() {
    this.props.setMessages(this.state.messages ? this.state.messages : '您请求的页面不存在', 'danger', 'popup')
  }

  render () {
    return (
      <div id="not-found">
        <Breadcrumb>错误消息</Breadcrumb>
        <main id="main" role="main">
        </main>
      </div>
    )
  }
}
